import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SubMenu from "@/components/SubMenu";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <Header />
        <SubMenu />
        <main className="flex flex-col text-sm leading-6 min-h-[calc(100vh-281px)] items-center justify-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
